---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-istio
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "{{ .Chart.AppVersion }}"
    networking.knative.dev/ingress-provider: istio
data:
  gateway.knative-serving.knative-ingress-gateway: {{ .Values.istio.externalIngressgateway}}.{{ .Values.istio.namespace}}.svc.cluster.local
  local-gateway.knative-serving.cluster-local-gateway: {{ .Values.istio.localIngressgateway}}.{{ .Values.istio.namespace}}.svc.cluster.local
  local-gateway.mesh: "mesh"

---
