---
apiVersion: v1
kind: Secret
metadata:
  name: istio-webhook-certs
  namespace: knative-serving
  labels:
    serving.knative.dev/release: "{{ .Chart.AppVersion }}"
    networking.knative.dev/ingress-provider: istio

---
