apiVersion: v2
name: knative-serving
description: A knative serving Helm chart for Kubernetes
type: application
version: 2.0.1
appVersion: v0.15.0
icon: https://avatars2.githubusercontent.com/u/35583233?s=200&v=4
