# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

core:
  domain: "example.com"
  activator:
    minAvailable: 1
    priorityClassName: ""
    name: "activator"
    autoscaling:
      minReplicas: 1
      maxReplicas: 20
      targetCPUUtilizationPercentage: 100
    resources: {}
  autoscaler:
    minAvailable: 1
    priorityClassName: ""
    replicaCount: 1
    name: "autoscaler"
    resources: {}
  controller:
    minAvailable: 1
    priorityClassName: ""
    name: "controller"
    resources: {}
  webhook:
    minAvailable: 1
    priorityClassName: ""
    name: "webhook"
    resources: {}
  podLabels: {}
  podAnnotations: {}
  tolerations: []
  nodeSelector: {}
  lifecycle: {}
  affinity: {}

istio:
  networking:
    minAvailable: 1
    name: "networking"
    resources: {}
  webhook:
    minAvailable: 1
    name: "webhook"
    resources: {}
  externalIngressgateway: "istio-ingressgateway"
  localIngressgateway: "cluster-local-gateway"
  namespace: "istio-system"
  podLabels: {}
  podAnnotations: {}
  tolerations: []
  nodeSelector: {}
  lifecycle: {}
  affinity: {}
  
