# Default values for ..
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

core:
  domain: "example.com"

istio:
  externalIngressgateway: "istio-ingressgateway"
  localIngressgateway: "cluster-local-gateway"
  namespace: "istio-system"


podLabels: {}
podAnnotations: {}
