apiVersion: v1
kind: Service
metadata:
  labels:
    app: autoscaler
    serving.knative.dev/release: "v0.14.0"
{{- include "knative-serving.labels" . | nindent 4 }}
  name: autoscaler
  namespace: knative-serving
spec:
  ports:
  - # Define metrics and profiling for them to be accessible within service meshes.
    name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  - name: http
    port: 8080
    targetPort: 8080
  - name: https-custom-metrics
    port: 443
    targetPort: 8443
  selector:
    app: autoscaler

---
