{{- if .Values.certmanager.enabled }}
apiVersion: v1
kind: Service
metadata:
  labels:
    app: networking-certmanager
    serving.knative.dev/release: "{{ .Chart.AppVersion }}"
    networking.knative.dev/certificate-provider: {{ .Values.certmanager.provider }}
  name: networking-certmanager
  namespace: knative-serving
spec:
  ports:
  - # Define metrics and profiling for them to be accessible within service meshes.
    name: http-metrics
    port: 9090
    targetPort: 9090
  - name: http-profiling
    port: 8008
    targetPort: 8008
  selector:
    app: networking-certmanager
---
{{- end }}
