apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    serving.knative.dev/release: "{{ .Chart.AppVersion }}"
{{- include "knative-serving.labels" . | nindent 4 }}
  name: {{ template "knative-serving.istio.networking.name" . }}
spec:
  selector:
    matchLabels:
      app: networking-istio
  minAvailable: {{ .Values.istio.networking.minAvailable }}
