{{- if .Values.istio.webhook.podDisruptionBudget.enabled }}
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  labels:
    serving.knative.dev/release: "{{ .Chart.AppVersion }}"
{{- include "knative-serving.labels" . | nindent 4 }}
  name: {{ template "knative-serving.istio.webhook.name" . }}
spec:
  selector:
    matchLabels:
      app: webhook
  minAvailable: {{ .Values.istio.webhook.podDisruptionBudget.minAvailable }}
{{- end }}
